/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedViThangRouteImport } from './routes/_authenticated/vi-thang'
import { Route as AuthenticatedGiaoDichRouteImport } from './routes/_authenticated/giao-dich'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViThangRoute = AuthenticatedViThangRouteImport.update({
  id: '/vi-thang',
  path: '/vi-thang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiaoDichRoute = AuthenticatedGiaoDichRouteImport.update({
  id: '/giao-dich',
  path: '/giao-dich',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/giao-dich': typeof AuthenticatedGiaoDichRoute
  '/vi-thang': typeof AuthenticatedViThangRoute
}
export interface FileRoutesByTo {
  '/giao-dich': typeof AuthenticatedGiaoDichRoute
  '/vi-thang': typeof AuthenticatedViThangRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/giao-dich': typeof AuthenticatedGiaoDichRoute
  '/_authenticated/vi-thang': typeof AuthenticatedViThangRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/giao-dich' | '/vi-thang'
  fileRoutesByTo: FileRoutesByTo
  to: '/giao-dich' | '/vi-thang' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/giao-dich'
    | '/_authenticated/vi-thang'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vi-thang': {
      id: '/_authenticated/vi-thang'
      path: '/vi-thang'
      fullPath: '/vi-thang'
      preLoaderRoute: typeof AuthenticatedViThangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/giao-dich': {
      id: '/_authenticated/giao-dich'
      path: '/giao-dich'
      fullPath: '/giao-dich'
      preLoaderRoute: typeof AuthenticatedGiaoDichRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGiaoDichRoute: typeof AuthenticatedGiaoDichRoute
  AuthenticatedViThangRoute: typeof AuthenticatedViThangRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGiaoDichRoute: AuthenticatedGiaoDichRoute,
  AuthenticatedViThangRoute: AuthenticatedViThangRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
